name: Manage by Issue
description: "Manage contributor vouch status via issue comments (vouch/denounce/unvouch)."

inputs:
  comment-id:
    description: "GitHub comment ID."
    required: true
  issue-id:
    description: "GitHub issue number."
    required: true
  allow-denounce:
    description: "Enable denounce handling to denounce users."
    required: false
    default: "true"
  allow-unvouch:
    description: "Enable unvouch handling to remove users."
    required: false
    default: "true"
  allow-vouch:
    description: "Enable vouch keyword handling to vouch for contributors."
    required: false
    default: "true"
  denounce-keyword:
    description: "Comma-separated list of keywords that trigger denouncing (default: denounce)."
    required: false
    default: ""
  dry-run:
    description: "Print what would happen without making changes."
    required: false
    default: "false"
  repo:
    description: "Repository in 'owner/repo' format (default: current repository)."
    required: false
    default: ""
  unvouch-keyword:
    description: "Comma-separated list of keywords that trigger unvouching (default: unvouch)."
    required: false
    default: ""
  vouch-keyword:
    description: "Comma-separated list of keywords that trigger vouching (default: vouch)."
    required: false
    default: ""
  vouched-file:
    description: "Path to the vouched contributors file (empty = auto-detect)."
    required: false
    default: ""

outputs:
  status:
    description: "Result status: vouched, denounced, unvouched, or unchanged"
    value: ${{ steps.run.outputs.status }}

runs:
  using: composite
  steps:
    - uses: hustcer/setup-nu@v3
      with:
        version: "*"

    - id: run
      shell: nu {0}
      run: |
        use "${{ github.action_path }}/../../vouch" *

        let vouch_kw = "${{ inputs.vouch-keyword }}" | split row "," | each { str trim } | where { $in | is-not-empty }
        let denounce_kw = "${{ inputs.denounce-keyword }}" | split row "," | each { str trim } | where { $in | is-not-empty }
        let unvouch_kw = "${{ inputs.unvouch-keyword }}" | split row "," | each { str trim } | where { $in | is-not-empty }

        let status = (gh-manage-and-push
          --type "issue"
          --id ${{ inputs.issue-id }}
          --comment-id "${{ inputs.comment-id }}"
          --repo "${{ inputs.repo || github.repository }}"
          --vouched-file "${{ inputs.vouched-file }}"
          --vouch-keyword $vouch_kw
          --denounce-keyword $denounce_kw
          --unvouch-keyword $unvouch_kw
          --allow-vouch=(${{ inputs.allow-vouch }} | into bool)
          --allow-denounce=(${{ inputs.allow-denounce }} | into bool)
          --allow-unvouch=(${{ inputs.allow-unvouch }} | into bool)
          --dry-run=(${{ inputs.dry-run }} | into bool)
        )
        $"status=($status)" | save --append $env.GITHUB_OUTPUT


